# ============================================================
# Script 12: Marginal contributions of measures in Pareto packages
# ============================================================
#
# Purpose
# -------
# This script estimates the package-level marginal contribution of each
# individual biosecurity measure that appears in at least one Pareto-optimal
# package.
#
# The analysis starts from two exported files:
#   1. package_net_benefits.csv
#      Contains simulated net benefits for each package across regions,
#      disease states, aggregation assumptions, and decision contexts.
#
#   2. package_pareto_frontier.csv
#      Contains the subset of packages identified as Pareto-optimal in the
#      previous frontier analysis.
#
# For each measure, the script:
#   - identifies Pareto-optimal packages that contain that measure;
#   - removes the measure from each package to define a counterfactual package;
#   - looks up the expected-value net benefit of the original package and the
#     counterfactual package;
#   - computes the marginal contribution as:
#
#       EV(original package) - EV(package without the measure)
#
#   - summarizes the distribution of those marginal contributions across all
#     Pareto packages containing the measure.
#
# Interpretation
# --------------
# A positive marginal contribution means that, on average, packages containing
# the measure perform better than the same packages with that measure removed.
# A negative marginal contribution means that the measure tends to reduce the
# package-level expected net benefit in the Pareto package contexts where it
# appears.
#
# Important modelling choice
# --------------------------
# This is a package-level comparison, not a state-by-state marginal-effect
# analysis. Net benefits are first collapsed to each package's expected value
# across all payoff rows, and marginal contributions are then calculated using
# those package-level summaries.
#
# Outputs
# -------
# The script writes:
#   - measure_marginal_contributions_pareto_package_level_summary.csv
#   - measure_marginal_contributions_boxplot.png
#
# The CSV provides numerical summaries. The plot shows the 5th to 95th
# percentile range, interquartile range, and median marginal contribution for
# each measure.
#
# ============================================================

library(data.table)
library(stringr)
library(ggplot2)

# ============================================================
# Input and output paths
# ============================================================

# These files are generated by upstream scripts in the package-analysis
# pipeline. The net-benefit file contains all package payoffs, while the
# Pareto file identifies the packages retained on the non-dominated frontier.
net_file <- "exports/package_net_benefits.csv"
pareto_file <- "exports/package_pareto_frontier.csv"

out_dir <- "exports/marginal_contribution"

out_csv <- file.path(
  out_dir,
  "measure_marginal_contributions_pareto_package_level_summary.csv"
)

out_plot <- file.path(
  out_dir,
  "measure_marginal_contributions_boxplot.png"
)

dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

# ============================================================
# 1. Load data
# ============================================================

# Load the full package net-benefit table and the Pareto-frontier table.
# data.table::fread() is used because these exported files can become large.
net_dt <- fread(net_file)
pareto_dt <- fread(pareto_file)

# ============================================================
# 2. Standardise package keys
# ============================================================

# Create a consistent package identifier in both datasets. Empty, missing, or
# explicitly labelled empty packages are all mapped to the same key so they can
# be matched reliably in later joins.
# Helper used to clean package labels before joins and comparisons.
make_package_key <- function(x) {
  fifelse(
    is.na(x) | x == "" | x == "empty_package",
    "empty_package",
    str_squish(x)
  )
}

net_dt[, package_key := make_package_key(package_contents)]
pareto_dt[, package_key := make_package_key(package_contents)]

# Keep the unique set of Pareto package keys. The total count is later used to
# express how frequently each measure appears among Pareto packages.
pareto_packages <- unique(pareto_dt$package_key)
n_total_pareto_packages <- length(pareto_packages)

# ============================================================
# 3. Collapse state-level payoffs to package-level EV
# ============================================================

# Each package has many payoff rows because benefits vary across simulated
# contexts. For this marginal-contribution analysis, those rows are collapsed to
# a package-level expected value and median net benefit.
package_ev <- net_dt[
  ,
  .(
    package_ev = mean(net_benefit_ref, na.rm = TRUE),
    package_median = median(net_benefit_ref, na.rm = TRUE),
    n_payoff_rows = .N
  ),
  by = package_key
]

# ============================================================
# 4. Keep Pareto packages as starting packages
# ============================================================

# Marginal contributions are only calculated for measures appearing in packages
# that were selected on the Pareto frontier. Non-frontier packages can still be
# used as counterfactuals after a measure is removed.
pareto_ev <- package_ev[
  package_key %in% pareto_packages
]

# ============================================================
# 5. Identify all measures in Pareto packages
# ============================================================

# Split the package labels into their component measures. The empty package is
# excluded because it contains no measure whose marginal contribution can be
# evaluated.
all_measures <- unique(
  unlist(
    str_split(
      pareto_ev[package_key != "empty_package", package_key],
      " \\+ "
    )
  )
)

all_measures <- sort(all_measures)

# ============================================================
# 6. Helper functions
# ============================================================

# has_measure() checks whether a package contains a specific measure.
# remove_measure() constructs the counterfactual package obtained by removing
# that measure. If no measures remain, the counterfactual is the empty package.
has_measure <- function(package_key, measure_name) {
  vapply(
    str_split(package_key, " \\+ "),
    function(x) measure_name %in% x,
    logical(1)
  )
}

remove_measure <- function(package_key, measure_to_remove) {
  vapply(
    str_split(package_key, " \\+ "),
    function(x) {
      remaining <- setdiff(x, measure_to_remove)
      
      if (length(remaining) == 0) {
        "empty_package"
      } else {
        paste(remaining, collapse = " + ")
      }
    },
    character(1)
  )
}

# ============================================================
# 7. Counterfactual lookup
# ============================================================

# Prepare a lookup table for counterfactual packages. After a measure is removed
# from a Pareto package, this table provides the expected value and median net
# benefit for the resulting package.
lookup <- package_ev[
  ,
  .(
    package_without_measure = package_key,
    cf_package_ev = package_ev,
    cf_package_median = package_median
  )
]

setkey(lookup, package_without_measure)

# ============================================================
# 8. Compute package-level marginal contributions
# ============================================================

# Loop over each measure found in Pareto packages. For every Pareto package that
# includes the measure, compare the package EV with the EV of the same package
# after removing that measure.
summary_list <- vector("list", length(all_measures))
names(summary_list) <- all_measures

for (m in all_measures) {
  
  message("Processing: ", m)
  
  # Retain only Pareto packages that contain the current measure.
  with_measure <- pareto_ev[
    has_measure(package_key, m)
  ]
  
  if (nrow(with_measure) == 0) {
    next
  }
  
  # Define the counterfactual package: the same package after removing the
  # current measure.
  with_measure[
    ,
    package_without_measure := remove_measure(package_key, m)
  ]
  
  # Join the counterfactual EV onto each original Pareto package.
  mc <- lookup[with_measure, on = "package_without_measure"]
  
  # Marginal contribution is the expected-value net benefit lost or gained when
  # the measure is removed from the package.
  mc[
    ,
    marginal_contribution_ev := package_ev - cf_package_ev
  ]
  
  # Store selected percentiles for plotting whiskers and boxes.
  q <- quantile(
    mc$marginal_contribution_ev,
    probs = c(0.05, 0.10, 0.25, 0.75, 0.90, 0.95),
    na.rm = TRUE
  )
  
  # Summarise the distribution of marginal contributions for this measure
  # across the Pareto packages in which it appears.
  summary_list[[m]] <- data.table(
    measure = m,
    n_pareto_packages = uniqueN(mc$package_key),
    pareto_frequency = uniqueN(mc$package_key) / n_total_pareto_packages,
    
    p05_marginal_contribution = q[[1]],
    p10_marginal_contribution = q[[2]],
    p25_marginal_contribution = q[[3]],
    median_marginal_contribution =
      median(mc$marginal_contribution_ev, na.rm = TRUE),
    mean_marginal_contribution =
      mean(mc$marginal_contribution_ev, na.rm = TRUE),
    p75_marginal_contribution = q[[4]],
    p90_marginal_contribution = q[[5]],
    p95_marginal_contribution = q[[6]],
    min_marginal_contribution =
      min(mc$marginal_contribution_ev, na.rm = TRUE),
    max_marginal_contribution =
      max(mc$marginal_contribution_ev, na.rm = TRUE),
    share_positive =
      mean(mc$marginal_contribution_ev > 0, na.rm = TRUE),
    share_negative =
      mean(mc$marginal_contribution_ev < 0, na.rm = TRUE)
  )
  
  rm(with_measure, mc, q)
  gc()
}

# ============================================================
# 9. Export summary CSV
# ============================================================

# Combine the per-measure summaries, rank measures by their median marginal
# contribution, and export the table for manuscript tables or supplementary
# material.
summary_list <- summary_list[!sapply(summary_list, is.null)]

summary_dt <- rbindlist(
  summary_list,
  use.names = TRUE,
  fill = TRUE
)

setorder(summary_dt, -median_marginal_contribution)

fwrite(summary_dt, out_csv)

# ============================================================
# 10. Plot horizontal box-whisker figure
# ============================================================

# Build a compact horizontal box-whisker style plot using the summary statistics
# already calculated above. The plot is not based on raw observations; instead,
# the 5th/25th/50th/75th/95th percentiles are drawn manually from summary_dt.
plot_dt <- as.data.frame(summary_dt)

plot_dt$measure <- factor(
  plot_dt$measure,
  levels = rev(plot_dt$measure)
)

p <- ggplot(plot_dt, aes(y = measure)) +
  
  # Vertical reference line: values to the right are positive marginal
  # contributions, while values to the left are negative.
  geom_vline(
    xintercept = 0,
    linetype = 2,
    color = "black",
    linewidth = 0.5
  ) +
  
  # Lower whisker: 5th to 25th percentile.
  geom_segment(
    aes(
      x = p05_marginal_contribution,
      xend = p25_marginal_contribution,
      yend = measure
    ),
    linewidth = 0.6,
    color = "black"
  ) +
  
  # Upper whisker: 75th to 95th percentile.
  geom_segment(
    aes(
      x = p75_marginal_contribution,
      xend = p95_marginal_contribution,
      yend = measure
    ),
    linewidth = 0.6,
    color = "black"
  ) +
  
  # Lower whisker: 5th to 25th percentile.
  geom_segment(
    aes(
      x = p05_marginal_contribution,
      xend = p05_marginal_contribution,
      y = as.numeric(measure) - 0.15,
      yend = as.numeric(measure) + 0.15
    ),
    linewidth = 0.6,
    color = "black"
  ) +
  
  geom_segment(
    aes(
      x = p95_marginal_contribution,
      xend = p95_marginal_contribution,
      y = as.numeric(measure) - 0.15,
      yend = as.numeric(measure) + 0.15
    ),
    linewidth = 0.6,
    color = "black"
  ) +
  
  # Interquartile range box: 25th to 75th percentile.
  geom_rect(
    aes(
      xmin = p25_marginal_contribution,
      xmax = p75_marginal_contribution,
      ymin = as.numeric(measure) - 0.32,
      ymax = as.numeric(measure) + 0.32
    ),
    fill = "#e9a2bb",
    color = "black",
    linewidth = 0.4,
    alpha = 0.85
  ) +
  
  # Median line inside the interquartile box.
  geom_segment(
    aes(
      x = median_marginal_contribution,
      xend = median_marginal_contribution,
      y = as.numeric(measure) - 0.32,
      yend = as.numeric(measure) + 0.32
    ),
    linewidth = 0.8,
    color = "black"
  ) +
  
  scale_x_continuous(
    name = "Marginal contribution (€/cow-year)",
    expand = expansion(mult = c(0.03, 0.06))
  ) +
  
  scale_y_discrete(
    name = NULL,
    expand = expansion(mult = c(0.12, 0.12))
  ) +
  
  labs(
    title = "Marginal contribution of measures within Pareto-optimal packages"
  ) + coord_cartesian(
    clip = "off"
  ) +
  
  theme_bw(base_size = 11) +
  
  theme(
    panel.grid = element_blank(),
    panel.border = element_rect(
      colour = "black",
      fill = NA,
      linewidth = 0.3
    ),
    plot.title = element_text(
      face = "bold",
      hjust = 0.5
    ),
    axis.text.y = element_text(
      size = 8,
      color = "black"
    ),
    axis.text.x = element_text(
      size = 9,
      color = "black"
    ),
    axis.title.x = element_text(
      size = 10,
      color = "black"
    ),
    plot.margin = margin(
      t = 10,
      r = 25,
      b = 10,
      l = 10
    )
  )

# Export the final figure at high resolution for manuscript use.
ggsave(
  out_plot,
  p,
  width = 8,
  height = 4,
  dpi = 600
)